version: '3'

services:
  react-app:
    build:
      context: ./DressGalleryUI
    ports:
      - "${REACT_APP_BACKEND_PORT:-3000}:${REACT_APP_BACKEND_PORT:-3000}"
    env_file:
      - ./DressGalleryUI/.env
    depends_on:
      - api-server

  api-server:
    build:
      context: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - ./.env
