services:
  react-app:
    build:
      context: ./DressGalleryUI
    ports:
      - "${REACT_APP_BACKEND_PORT:-3000}:${REACT_APP_BACKEND_PORT:-3000}"
    env_file:
      - ./DressGalleryUI/.env
    depends_on:
      - api-server
    networks:
      - cloth-gallery

  api-server:
    build:
      context: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - ./.env
    networks:
      - cloth-gallery

networks:
  cloth-gallery:
    driver: bridge
